from pathlib import Path

events_dir: Path = None  # type: ignore[assignment]
actions_dir: Path = None  # type: ignore[assignment]
tss_dir: Path = None  # type: ignore[assignment]
tpsfs_dir: Path = None  # type: ignore[assignment]
texthis_dir: Path = None  # type: ignore[assignment]
texthis_json_dir: Path = None  # type: ignore[assignment]
texthis_txt_dir: Path = None  # type: ignore[assignment]
texthis_visual_dir: Path = None  # type: ignore[assignment]
stats_dir: Path = None  # type: ignore[assignment]
senhis_dir: Path = None  # type: ignore[assignment]
senhis_json_dir: Path = None  # type: ignore[assignment]
senhis_txt_dir: Path = None  # type: ignore[assignment]
senhis_visual_dir: Path = None  # type: ignore[assignment]
senhis_parses_dir: Path = None  # type: ignore[assignment]
dependency_senhis_parses_dir: Path = None  # type: ignore[assignment]
constituency_senhis_parses_dir: Path = None  # type: ignore[assignment]
transhis_dir: Path = None  # type: ignore[assignment]
dependency_transhis_dir: Path = None  # type: ignore[assignment]
constituency_transhis_dir: Path = None  # type: ignore[assignment]
