from supar.utils import Dataset

class Parser:
    @classmethod
    def load(cls, path: str) -> Parser: ...
    def predict(
        self, data: str, lang: str = ..., prob: bool = ..., verbose: bool = ...
    ) -> Dataset: ...
